// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projectTasks1;

#nullable disable

namespace projectTasks1.Migrations
{
    [DbContext(typeof(TareaContext))]
    [Migration("20241228025750_Dataintables")]
    partial class Dataintables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("projectTasks1.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("ffaca5fa-db0c-4acc-8300-dda804df4177"),
                            Descripcion = "Desarrollo",
                            Nombre = "Tecnologia",
                            Peso = 1
                        },
                        new
                        {
                            CategoriaId = new Guid("bdb76bbc-7604-422c-9717-e735eb233290"),
                            Descripcion = "Logistica",
                            Nombre = "Tecnologia",
                            Peso = 2
                        },
                        new
                        {
                            CategoriaId = new Guid("ff2e1696-e1c6-43c7-a789-152dcc93deef"),
                            Descripcion = "Administracion",
                            Nombre = "Tecnologia",
                            Peso = 1
                        });
                });

            modelBuilder.Entity("projectTasks1.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("a30569a5-ab8f-4d17-8b46-013eca1d77c2"),
                            CategoriaId = new Guid("ffaca5fa-db0c-4acc-8300-dda804df4177"),
                            Descripcion = "Desarrollo de software para la empresa",
                            FechaCreacion = new DateTime(2024, 12, 28, 2, 57, 50, 262, DateTimeKind.Utc).AddTicks(1270),
                            PrioridadTarea = 1,
                            Titulo = "Desarrollo de software"
                        },
                        new
                        {
                            TareaId = new Guid("2ec0f884-d423-4f7c-ab22-88ac8f61882d"),
                            CategoriaId = new Guid("bdb76bbc-7604-422c-9717-e735eb233290"),
                            Descripcion = "Desarrollo de aplicaciones para la empresa",
                            FechaCreacion = new DateTime(2024, 12, 28, 2, 57, 50, 262, DateTimeKind.Utc).AddTicks(1270),
                            PrioridadTarea = 0,
                            Titulo = "Desarrollo de aplicaciones"
                        },
                        new
                        {
                            TareaId = new Guid("0df62d8a-30be-450a-aee8-556361fcf51f"),
                            CategoriaId = new Guid("ff2e1696-e1c6-43c7-a789-152dcc93deef"),
                            Descripcion = "Desarrollo de paginas web para la empresa",
                            FechaCreacion = new DateTime(2024, 12, 28, 2, 57, 50, 262, DateTimeKind.Utc).AddTicks(1270),
                            PrioridadTarea = 2,
                            Titulo = "Desarrollo de paginas web"
                        });
                });

            modelBuilder.Entity("projectTasks1.Models.Tarea", b =>
                {
                    b.HasOne("projectTasks1.Models.Categoria", "categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("projectTasks1.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
